# Reference:
# mkdocs - https://www.mkdocs.org/user-guide/configuration/
# mkdocs material theme - https://squidfunk.github.io/mkdocs-material/getting-started/#configuration

# Project Information
site_name: AlgoBulls Help Site
site_description: Help Site for using the AlgoBulls Platform | A Trading platform with complete end-to-end solution - ready-to-use Stock Market Knowledge & Fully Automated Algorithmic Trading!
site_author: AlgoBulls
site_url: https://help.algobulls.com

# GitHub Repo information
repo_url: https://github.com/algobulls/algobulls_help_site

#theme:
#  name: material
#  favicon: 'imgs/favicon.svg'
#  logo: 'imgs/site_logo_white.svg'
#  palette:
#    primary: blue
#    accent: blue
#  language: en
#  features:
#    - navigation.expand
#    - navigation.top
#   - tabs (if you want tabs at the top instead of a side-menu)

theme:
  name: material
  favicon: 'imgs/favicon.svg'
  logo: 'imgs/site_logo_white.svg'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
#        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
#        icon: material/weather-sunny
        name: Switch to light mode
  language: en
  features:
    - navigation.expand
    - navigation.top

copyright: Copyright © 2020 | All Rights Reserved | AlgoBulls Technologies Private Limited

# Navigation
nav:
  - Home: 'index.md'
  - 'FAQ': 'member/faq.md'
  - 'Website Manual':
      - 'Marketplace': 'member/marketplace.md'
      - 'Dashboard': 'member/dashboard.md'
      - 'Portfolio': 'member/portfolio.md'
      - 'Paper Trading & Backtesting': 'member/paperback.md'
      - 'Manage Strategies': 'member/custom-strategies.md'
      - 'Live Reports':
          - 'P & L Book': 'member/Books/pnl.md'
          - 'Trade Book': 'member/Books/tradebook.md'
          - 'Fund Book': 'member/Books/fundbook.md'
      - 'Settings':
          - 'General': 'member/Settings/general-settings.md'
          - 'Broking': 'member/Settings/broking-settings.md'
      - 'Plans & Wallet': 'member/wallet.md'
#      - 'Navigation Bar': 'member/nav-bar.md'
  - 'Features':
      - 'P&L Tracker': 'member/pnltracker.md'
      - 'Tweak': 'member/tweak.md'
  - 'Broker Information':
      - 'ALICEBLUE': 'broker/aliceblue.md'
      - 'ALPACA': 'broker/alpaca.md'
      - 'ANGELBROKING': 'broker/angelbroking.md'
      - 'ARHAM WEALTH': 'broker/arhamwealth.md'
#      - 'ASTHA': 'broker/astha.md'
#      - 'FYERS': 'broker/fyers.md'
      - 'INDIRA SECURITIES': 'broker/indirasecurities.md'
      - 'JAINAM DUCK': 'broker/jainamduck.md'
      - 'KOTAK SECURITIES': 'broker/kotaksecurities.md'
      - 'MASTERTRUST': 'broker/mastertrust.md'
      - 'RUDRA SHARES': 'broker/rudrashares.md'
      - 'SHAREKHAN': 'broker/sharekhan.md'
#      - 'TRADEBULLS': 'broker/tradebulls.md'
      - 'ZEBU': 'broker/zebu.md'
      - 'ZERODHA': 'broker/zerodha.md'
  - 'Developer Options': 'developers.md'

plugins:
  - search                                  # necessary for search to work
  - git-revision-date-localized:            # When enabled, the respective 'Last Updated' date is automatically added at the bottom of each page. Docs: https://squidfunk.github.io/mkdocs-material/plugins/revision-date/
      type: timeago


google_analytics:
  - 'UA-147658856-2'
  - 'auto'

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/algobulls
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/algobullsalgotrading
    - icon: fontawesome/brands/github-alt
      link: https://github.com/algobulls/
  disqus: algobulls


markdown_extensions:
  - admonition              # Add note, tip, question, warning, error, etc. Docs: https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - toc:                    # Docs: https://squidfunk.github.io/mkdocs-material/extensions/permalinks/
      permalink: true
  - pymdownx.tabbed
  - pymdownx.superfences