# Reference:
# mkdocs - https://www.mkdocs.org/user-guide/configuration/
# mkdocs material theme - https://squidfunk.github.io/mkdocs-material/getting-started/#configuration

# Project Information
site_name: AlgoBulls Help Site
site_description: Help Site for using the AlgoBulls Platform | A Trading platform with complete end-to-end solution - ready-to-use Stock Market Knowledge & Fully Automated Algorithmic Trading!
site_author: AlgoBulls
site_url: https://help.algobulls.com

# GitHub Repo information
repo_url: https://github.com/algobulls/algobulls_help_site

#theme:
#  name: material
#  favicon: 'imgs/favicon.svg'
#  logo: 'imgs/site_logo_white.svg'
#  palette:
#    primary: blue
#    accent: blue
#  language: en
#  features:
#    - navigation.expand
#    - navigation.top
#   - tabs (if you want tabs at the top instead of a side-menu)

theme:
  name: material
  favicon: 'imgs/favicon.svg'
  logo: 'imgs/site_logo_white.svg'
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch-off-outline
#        icon: material/weather-night
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
#        icon: material/weather-sunny
        name: Switch to light mode
  language: en
  features:
    - navigation.expand
    - navigation.top

copyright: Copyright © 2020 | All Rights Reserved | AlgoBulls Technologies Private Limited

# Using this to control the style used for linking to pages within documentation. Without this option, links are broken when docs are generated using `mkdocs build`.
# For more information: https://www.mkdocs.org/user-guide/configuration/#use_directory_urls 
use_directory_urls: false

# Navigation
nav:
  - Home: 'index.md'
  - 'FAQ': 'member/faq.md'
  - 'Website Manual':
      - 'Dashboard': 'member/dashboard.md'
      - 'Choose Strategy': 'member/choose-strategy.md'
      - 'My Portfolio':
          - 'Live Trading': 'member/live-trading.md'
          - 'Virtual Trading': 'member/virtual-trading.md'
      - 'My Strategies': 'member/my-strategies.md'
      - 'Strategy Card': 'member/strategy-card.md'
      - 'Live Reports':
          - 'P & L Book': 'member/Books/pnl.md'
          - 'Trade Book': 'member/Books/tradebook.md'
          - 'Fund Book': 'member/Books/fundbook.md'
      - 'Broking Details': 'member/broking-details.md'
      - 'Plans & Wallet': 'member/wallet.md'
      - 'Settings': 'member/settings.md'
  - 'Features':
      - 'P&L Tracker': 'member/pnltracker.md'
      - 'Tweak': 'member/tweak.md'
      - 'Test & Live Mode': 'member/test-to-live-mode.md'
      - 'Broker Calculator': 'member/brokerage-calculator.md'
  - 'Broker Information':
      - '5PAISA': 'broker/fivepaisa.md'
      - 'AC AGARWAL': 'broker/acagarwal.md'
      - 'ALICEBLUE': 'broker/aliceblue.md'
      - 'ALPACA': 'broker/alpaca.md'
      - 'ANGELBROKING': 'broker/angelbroking.md'
      - 'ARHAM WEALTH': 'broker/arhamwealth.md'
      - 'EDELWEISS': 'broker/edelweiss.md'
      - 'FINDOC': 'broker/findoc.md'
      - 'FINVASIA': 'broker/finvasia.md'
#      - 'ICICI SECURITIES': 'broker/icicisecurities.md'
      - 'IIFL SECURITIES': 'broker/iifl.md'
      - 'INDIRA SECURITIES': 'broker/indirasecurities.md'
      - 'JAINAM DUCK': 'broker/jainamduck.md'
      - 'KOTAK SECURITIES': 'broker/kotaksecurities.md'
      - 'MASTERTRUST': 'broker/mastertrust.md'
      - 'RUDRA SHARES': 'broker/rudrashares.md'
      - 'SHAREKHAN': 'broker/sharekhan.md'
      - 'ZEBU': 'broker/zebu.md'
      - 'ZERODHA': 'broker/zerodha.md'
  - 'Archive/V1':
    - 'Website Manual':
        - 'Marketplace': 'archive_v1/member/marketplace.md'
        - 'Dashboard': 'archive_v1/member/dashboard.md'
        - 'Portfolio': 'archive_v1/member/portfolio.md'
        - 'Paper Trading & Backtesting': 'archive_v1/member/paperback.md'
        - 'Manage Strategies': 'archive_v1/member/custom-strategies.md'
        - 'Live Reports':
            - 'P & L Book': 'archive_v1/member/Books/pnl.md'
            - 'Trade Book': 'archive_v1/member/Books/tradebook.md'
            - 'Fund Book': 'archive_v1/member/Books/fundbook.md'
        - 'Settings':
            - 'General': 'archive_v1/member/Settings/general-settings.md'
            - 'Broking': 'archive_v1/member/Settings/broking-settings.md'
        - 'Plans & Wallet': 'archive_v1/member/wallet.md'
  #      - 'Navigation Bar': 'archive_v1/member/nav-bar.md'
    - 'Features':
        - 'P&L Tracker': 'archive_v1/member/pnltracker.md'
        - 'Tweak': 'archive_v1/member/tweak.md'
    - 'Broker Information':
        - '5PAISA': 'archive_v1/broker/fivepaisa.md'
        - 'AC AGARWAL': 'archive_v1/broker/acagarwal.md'
        - 'ALICEBLUE': 'archive_v1/broker/aliceblue.md'
        - 'ALPACA': 'archive_v1/broker/alpaca.md'
        - 'ANGELBROKING': 'archive_v1/broker/angelbroking.md'
        - 'ARHAM WEALTH': 'archive_v1/broker/arhamwealth.md'
        - 'EDELWEISS': 'archive_v1/broker/edelweiss.md'
  #      - 'ASTHA': 'archive_v1/broker/astha.md'
  #      - 'FYERS': 'archive_v1/broker/fyers.md'
        - 'ICICI SECURITIES': 'archive_v1/broker/icicisecurities.md'
        - 'IIFL SECURITIES': 'archive_v1/broker/iifl.md'
        - 'INDIRA SECURITIES': 'archive_v1/broker/indirasecurities.md'
        - 'JAINAM DUCK': 'archive_v1/broker/jainamduck.md'
        - 'KOTAK SECURITIES': 'archive_v1/broker/kotaksecurities.md'
        - 'MASTERTRUST': 'archive_v1/broker/mastertrust.md'
        - 'RUDRA SHARES': 'archive_v1/broker/rudrashares.md'
        - 'SHAREKHAN': 'archive_v1/broker/sharekhan.md'
  #      - 'TRADEBULLS': 'archive_v1/broker/tradebulls.md'
        - 'ZEBU': 'archive_v1/broker/zebu.md'
        - 'ZERODHA': 'archive_v1/broker/zerodha.md'
  - 'Developer Options': 'developers.md'

plugins:
  - search                                  # necessary for search to work
  - git-revision-date-localized:            # When enabled, the respective 'Last Updated' date is automatically added at the bottom of each page. Docs: https://squidfunk.github.io/mkdocs-material/plugins/revision-date/
      type: timeago


#google_analytics:
#  - 'UA-147658856-2'
#  - 'auto'

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/company/algobulls
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/algobullsalgotrading
    - icon: fontawesome/brands/github-alt
      link: https://github.com/algobulls/
  disqus: algobulls
  analytics:
    provider: google
    property: UA-147658856-2


markdown_extensions:
  - admonition              # Add note, tip, question, warning, error, etc. Docs: https://squidfunk.github.io/mkdocs-material/extensions/admonition/
  - toc:                    # Docs: https://squidfunk.github.io/mkdocs-material/extensions/permalinks/
      permalink: true
  - pymdownx.tabbed
  - pymdownx.superfences